### PR TITLE
Added file structure and required rb and spec files to the project.

### PR DESCRIPTION
**Pull request by lacuchilla**
Started work on initialize method.

### CODE REVIEW

**Comment by kariabancroft** [comment]
Why do you have a spec/farmar/market_spec.rb and a spec/far_mar/market_spec.rb file?

**Comment by kariabancroft** [comment]
Please add a product, sale and vendor spec that looks similar to what you have for the test in your market spec file

**Comment by lacuchilla** [comment]
I updated the other three specs to include a test similar to what I had in my market spec file.

**Comment by kariabancroft** [comment]
Please take a look at your folder structure, it looks like you have some files in a `far_mar` folder and others in a `farmar` folder. They need to be in the same place.

**Comment by lacuchilla** [comment]
Deleted the extra farmar folder and updated the specs in the far_mar folder.

**Comment by kariabancroft** [comment]
:+1:

**Pull request merged**
